version: "3.9"

services:
  iris-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'iris-rabbitmq'
    hostname: iris-rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    deploy:
      mode: "replicated"
      replicas: 1
      restart_policy:
        # condition: "always"
        delay: 5s
        window: 120s
    networks:
        - iris_network

  iris-app:
    image: registry.dataak.com:5000/iris:${IMAGE_TAG}
    container_name: 'iris-app'
    entrypoint: ["/usr/bin/supervisord"]    
    ports:
      - 8080:8080
    environment:
      - RABBITMQ_HOST=iris-rabbitmq
    depends_on:
      - iris-rabbitmq
    links:
      - iris-rabbitmq
    deploy:
      mode: "replicated"
      replicas: 1
      restart_policy:
        # condition: "always"
        delay: 5s
        window: 120s
    networks:
        - iris_network
        
networks:
  iris_network: